### ISSUE TITLE
clight does not start

### ISSUE THREAD

**Issue by vivien** [FedeDP/Clight#41]
Hi! Great initiative, especially since there's no non-Xorg standard tool to write backlight sysfs attributes. I've install both clight{,d}-git AUR packages, but there are a few errors. clight-git post install message says to enable `systemctl --user enable clight.timer` but there's not such unit file.

Then I've started/enabled the systemd system service for clightd with:
````
sudo systemctl enable clightd.service
sudo systemctl start clightd.service
````

but I get this while running clight:
````
$ clight
Config file /home/vivien/.config/clight.conf not found.
check(): Connection reset by peer
Upower appears to be unsupported.
check_clightd_version(): Transport endpoint is not connected
No clightd found. Clightd is a mandatory dep.
No functional module is running. Nothing to do...leaving.
````

I know clight wants to be zero-conf, so I'm wondering what's wrong! :-)

I'm currently running Archlinux without DM/DE, only systemd-logind, wayland and Sway 0.15. I'm not expecting gamma to work until I upgrade to Sway 1.0, but in the meantime, automatic control of the brightness would make me happy.

P.S.: is it clightd's job to remember the backlight brightness value and reset on next boot or not? This is what systemd-backlight is doing, I'm wondering if it must be disabled when clightd is enabled or not.

P.P.S.: I like the idea of using the webcam to capture ambient light, but I'm a paranoid user with a ThinkShutter to block it when not in use. Does clight ignore a black capture or would that mess up my brightness settings? What I'm imagining doing is opening the cam shutter when I want accurate settings from clightd and eventually manually trigger an update with clight.

Thank you!

**Comment by FedeDP** [comment]
Hi, thanks for opening the issue!

> clight-git post install message says to enable systemctl --user enable clight.timer but there's not such unit file.

Sorry, i forgot to update install script too.  I will as soon as i get home :)
Here it is right now: [clight.install](https://github.com/FedeDP/Clight/blob/master/Arch/clight.install).  

> but I get this while running clight:

It seems that there is some issues with your dbus daemon. What is output of `systemctl status clightd.service`?
And, if clightd status is fine, can you try a 
`busctl call org.clightd.clightd /org/clightd/clightd/Sensor org.clightd.clightd.Sensor Capture "si" "" 5`
It should capture 5 frames from webcam and return their average brightness values.

> I'm not expecting gamma to work until I upgrade to Sway 1.0
Gamma is still not working on wayland/wlroots as i haven't got the time yet to experiment with wayland protocols. If you, by any chance, are willing to take on this job, it would be great! :)  

> P.S.: is it clightd's job to remember the backlight brightness value and reset on next boot or not? This is what systemd-backlight is doing, I'm wondering if it must be disabled when clightd is enabled or not.

No, as clight will set new backlight (matching ambient brightness) as soon as it starts; thus it is quite useless to reset last (possibly wrong for current ambient brightness) backlight level.

> Does clight ignore a black capture or would that mess up my brightness settings?  

Unfortunately it won't ignore it because a black capture can also mean a very dark room.  
There is no more a "capture and leave" clight's mode. A couple of months ago it was there, but it was superseded by new clight bus api.  
You can obviously build your own script for clightd to reach the same, and bind it to a shortcut.  
Have a look at: https://github.com/FedeDP/Clightd/wiki/Devel (last part).

**Comment by vivien** [comment]
After installing clightd-git and clight-git, clightd.service seem to be enable but inactive (normal I guess since it has to be enable via bus). I start it manually and I get:
````
$ systemctl status clightd.service
● clightd.service - Bus service to manage various screen related properties (gamma, dpms, backlight)
   Loaded: loaded (/usr/lib/systemd/system/clightd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-11-16 10:42:27 EST; 16min ago
 Main PID: 5331 (clightd)
    Tasks: 1 (limit: 4915)
   Memory: 1.0M
   CGroup: /system.slice/clightd.service
           └─5331 /usr/lib/clightd/clightd
````
but still clight shows:
````
$ clight
Config file /home/vivien/.config/clight.conf not found.
check(): Connection reset by peer
Upower appears to be unsupported.
check_clightd_version(): Transport endpoint is not connected
No clightd found. Clightd is a mandatory dep.
No functional module is running. Nothing to do...leaving.
````

But the bus seems to be working:
````
$  busctl call org.clightd.clightd /org/clightd/clightd/Sensor org.clightd.clightd.Sensor Capture "si" "" 5
sad "/dev/video0" 5 0.452035 0.452035 0.452035 0.452035 0.452035
````

Also, it seems that clight is only meant to temporary override the daemon behavior. If so, how can I override temporarily the brightness values? I'd like to bind the brightness keys of the laptop to use clight(d).

**Comment by FedeDP** [comment]
> But the bus seems to be working:

That is weird though. It seems clight cannot connect to clightd (or to the bus altogether).  
I will have a look at it; but this is like the first time i see an issue of this kind.  

> Also, it seems that clight is only meant to temporary override the daemon behavior. If so, how can I override temporarily the brightness values? I'd like to bind the brightness keys of the laptop to use clight(d).

What do you mean by "overriding daemon behaviour"? Clightd is a backend daemon that offers some functionalities. It does nothing by itself. Clight uses clightd.   
But as i said, if you wish not to leave your camera uncovered all the time, and just trigger a "backlight calibration" through a binded key when you need it, you can just create a small bash script that actually sort of replicates clight behaviour (Clight tries to be much smarter, letting users set their "ambient-brightness-to-backlight-level" curve, and does much more things obviously).

**Comment by vivien** [comment]
Here's my systemd user environment:
````
...
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
...
LANG=en_US.UTF-8
SHELL=/bin/bash
USER=vivien
...
````

> Clightd is a backend daemon that offers some functionalities. It does nothing by itself. Clight uses clightd.

Oh, OK. I thought the logic was in the daemon, I understand now. Does it mean you never use your brightness keys anymore? There are cases I can think of where you want to temporary raise your screen brightness depending on the content (e.g. a dark picture) and I though `clight` could be used for that.

(Note: I've created a separate issue #42 to talk about out-of-the-box handling of camera shutters.)

**Comment by FedeDP** [comment]
Ok, i could reproduce the issue; it seems to be non-X11, ie: it happens on both tty and wayland. 
I have no idea what's happening though; i'm trying to find any bug report anywhere...  

I'll keep you updated! Sorry for the inconvenience!

**Comment by FedeDP** [comment]
@vivien  Can you try once more after pulling latest commit?
I could not reproduce it anymore after latest changes.

**Comment by vivien** [comment]
I'll test as soon as the AUR packages are up to date!

**Comment by FedeDP** [comment]
You can just re-install clightd and clight once more, as they are "-git" packages, their rebuild will also update them to latest git sources :)

**Comment by vivien** [comment]
Oops, I thought the revision was hardcoded... Re-installed and...
````
$ clight 
Config file /home/vivien/.config/clight.conf not found.
Clightd found, version: 2.4.
Ambient brightness: 0.331341
New backlight pct value: 0.512145
````
Fixed! Thank you for the quick fix!

I have a few questions:
1. What's upower used for?
2. Should clight be shipped with a systemd user service file so that one without DE/DM could enable?
3. Can you handle the keyboard backlight has well?

I'm closing the issue, thanks!

**Comment by FedeDP** [comment]
> I have a few questions. Should clight be shipped with a systemd user service file so that one without DE/DM could enable?

It was shipped with a systemd file. The issue is that systemd user session still does not handle much fine programs that need xorg display or whatever (clight for gamma); thus clight used to ship a timer unit too, that delayed clight startup of 5/10s.  
I didn't really like this solution as the delay is obviously not much agnostic (5s on my SSD is ok, but what about that slow HD that takes 45s to load X environment?).

>  Can you handle the keyboard backlight has well?

Clight does not handle keyboard backlight right now. Its support is quite easy to add, but i never added as i cannot test it.  
If you are willing to test, please open a new issue tracking this feature :)

Hoe you enjoy it!

**Comment by vivien** [comment]
I opened #44 for the backlit support.

Can you show me the systemd user service that used to be shipped with clight? I understand the dependency is still tricky to define, but at least I can start it manually during the day.

**Comment by FedeDP** [comment]
You can find them /service + timer) here: https://github.com/FedeDP/Clight/tree/2b2d6c56ee338a97411d732f02e16c3e4d8ac23f/Extra/systemd
